import { i18n } from '../../../plugins/i18n.js';
import MDRBaseView   from './MDRBaseView.vue';
import MDRListView   from './MDRListView.vue';
import MDRDetailView from './MDRDetailView.vue';

i18n.global.mergeLocaleMessage('vi', {
  mdr: {
    loading: 'Đang tải...',
    cancel: 'Hủy',
    error: 'Đã xảy ra lỗi',
    menu: 'MDR Builder',
    list: {
      title: 'Hồ sơ chất lượng bàn giao (MDR)',
      subtitle: 'Manufacturing Data Record — gói hồ sơ bàn giao',
      create: 'Tạo hồ sơ MDR',
      detail: 'Chi tiết',
      filter: 'Lọc',
      empty: 'Chưa có hồ sơ MDR nào',
      allStatus: 'Tất cả trạng thái',
    },
    create: {
      title: 'Tạo hồ sơ MDR mới',
      creating: 'Đang tạo...',
      nameRequired: 'Tên hồ sơ là bắt buộc',
      error: 'Lỗi tạo hồ sơ MDR',
      seedNote: 'Hệ thống sẽ tự tạo 16 nhóm danh mục tiêu chuẩn cho hồ sơ.',
    },
    detail: {
      title: 'Chi tiết hồ sơ MDR',
      subtitle: 'Danh mục tài liệu & độ hoàn thiện hồ sơ',
      back: 'Danh sách',
      categories: 'Danh mục tài liệu (Checklist)',
      missingSummary: 'danh mục bắt buộc còn thiếu',
      optional: 'Tùy chọn',
      missing: 'THIẾU',
      addDoc: 'Thêm tài liệu',
      docAdded: 'Đã thêm tài liệu',
      noDocs: 'Chưa có tài liệu',
      viewFile: 'Xem file',
      markPresent: 'Đánh dấu đã có',
      marked: 'Đã cập nhật',
      rescan: 'Quét lại độ hoàn thiện',
      rescanOk: 'Đã quét lại',
      compile: 'Biên dịch PDF',
      compileOk: 'Đã tạo PDF gộp',
      submit: 'Đóng gói & nộp (.zip)',
      submitOk: 'Đã tạo gói nộp',
      transmittal: 'Phiếu chuyển giao tài liệu',
      transmittalList: 'Lịch sử chuyển giao',
      create: 'Tạo phiếu',
      transOk: 'Đã tạo phiếu chuyển giao',
      docNameRequired: 'Tên tài liệu là bắt buộc',
      clientRequired: 'Tên khách hàng là bắt buộc',
      fileLinkPlaceholder: 'Đường dẫn file (http://...)',
    },
    field: {
      name: 'Tên hồ sơ',
      project: 'Dự án',
      status: 'Trạng thái',
      completion: 'Độ hoàn thiện',
      action: 'Thao tác',
      docName: 'Tên tài liệu',
      fileLink: 'Đường dẫn file',
      sourceModule: 'Module nguồn',
      transNo: 'Số phiếu',
      client: 'Khách hàng',
      docCount: 'Số tài liệu',
      issuedAt: 'Ngày phát hành',
      purpose: 'Mục đích',
      remarks: 'Ghi chú',
    },
    status: { draft: 'Nháp', in_progress: 'Đang xử lý', ready: 'Sẵn sàng', submitted: 'Đã nộp' },
  },
});

i18n.global.mergeLocaleMessage('en', {
  mdr: {
    loading: 'Loading...',
    cancel: 'Cancel',
    error: 'An error occurred',
    menu: 'MDR Builder',
    list: {
      title: 'Manufacturing Data Records (MDR)',
      subtitle: 'Manufacturing Data Record packages',
      create: 'Create MDR',
      detail: 'Details',
      filter: 'Filter',
      empty: 'No MDR dossiers yet',
      allStatus: 'All statuses',
    },
    create: {
      title: 'Create new MDR dossier',
      creating: 'Creating...',
      nameRequired: 'Dossier name is required',
      error: 'Failed to create MDR dossier',
      seedNote: 'The system will auto-create the 16 standard categories.',
    },
    detail: {
      title: 'MDR Dossier Details',
      subtitle: 'Document checklist & dossier completion',
      back: 'List',
      categories: 'Document checklist',
      missingSummary: 'required categories missing',
      optional: 'Optional',
      missing: 'MISSING',
      addDoc: 'Add document',
      docAdded: 'Document added',
      noDocs: 'No documents',
      viewFile: 'View file',
      markPresent: 'Mark present',
      marked: 'Updated',
      rescan: 'Rescan completeness',
      rescanOk: 'Rescanned',
      compile: 'Compile PDF',
      compileOk: 'PDF bundle created',
      submit: 'Build submission (.zip)',
      submitOk: 'Submission package created',
      transmittal: 'Document Transmittal',
      transmittalList: 'Transmittal history',
      create: 'Create',
      transOk: 'Transmittal created',
      docNameRequired: 'Document name is required',
      clientRequired: 'Client name is required',
      fileLinkPlaceholder: 'File link (http://...)',
    },
    field: {
      name: 'Dossier name', project: 'Project', status: 'Status', completion: 'Completion',
      action: 'Action', docName: 'Document name', fileLink: 'File link', sourceModule: 'Source module',
      transNo: 'Transmittal No', client: 'Client', docCount: 'Doc count', issuedAt: 'Issued at',
      purpose: 'Purpose', remarks: 'Remarks',
    },
    status: { draft: 'Draft', in_progress: 'In progress', ready: 'Ready', submitted: 'Submitted' },
  },
});

export default function registerMDRFrontend(app, router) {
  router.addRoute({
    path: '/mdr',
    component: MDRBaseView,
    children: [
      { path: '',    name: 'MDRList',   component: MDRListView },
      { path: ':id', name: 'MDRDetail', component: MDRDetailView },
    ],
  });
}
