import { i18n } from '../../../plugins/i18n.js';
import CalibrationBaseView from './CalibrationBaseView.vue';
import CalibrationListView from './CalibrationListView.vue';

i18n.global.mergeLocaleMessage('vi', {
  calibration: {
    masterLog: 'Sổ hiệu chuẩn thiết bị (ILS-QAC-F01)',
    subtitle: 'Quản lý hiệu chuẩn thiết bị đo lường',
    totalDevices: 'Tổng thiết bị',
    expiringSoon: 'Sắp hết hạn',
    expiredCount: 'Hết hạn',
    addDevice: 'Thêm thiết bị',
    editDevice: 'Sửa thiết bị',
    addRecord: 'Ghi hiệu chuẩn',
    searchPlaceholder: 'Tìm mã/tên thiết bị...',
    allStatus: 'Tất cả trạng thái',
    filter: 'Lọc',
    print: 'In',
    deviceCode: 'Mã thiết bị',
    name: 'Tên thiết bị',
    type: 'Loại',
    location: 'Vị trí',
    dueDate: 'Hạn hiệu chuẩn',
    calibratedDate: 'Ngày hiệu chuẩn',
    certificateNo: 'Số chứng nhận',
    result: 'Kết quả',
    calibratedBy: 'Đơn vị hiệu chuẩn',
    status: 'Trạng thái',
    statusHsd: 'Hạn sử dụng',
    valid: 'Còn hạn',
    expiring: 'Sắp hết hạn',
    expired: 'Hết hạn',
    unknown: 'Chưa hiệu chuẩn',
    actions: 'Thao tác',
    edit: 'Sửa',
    save: 'Lưu',
    saving: 'Đang lưu...',
    cancel: 'Hủy',
    loading: 'Đang tải...',
    empty: 'Chưa có thiết bị nào',
    requiredFields: 'Vui lòng nhập đủ thông tin bắt buộc',
    saved: 'Đã lưu',
    saveError: 'Lỗi khi lưu',
  },
});

i18n.global.mergeLocaleMessage('en', {
  calibration: {
    masterLog: 'Calibration Master Log (ILS-QAC-F01)',
    subtitle: 'Measurement & test equipment calibration',
    totalDevices: 'Total devices',
    expiringSoon: 'Expiring soon',
    expiredCount: 'Expired',
    addDevice: 'Add device',
    editDevice: 'Edit device',
    addRecord: 'Add calibration',
    searchPlaceholder: 'Search code/name...',
    allStatus: 'All status',
    filter: 'Filter',
    print: 'Print',
    deviceCode: 'Device code',
    name: 'Device name',
    type: 'Type',
    location: 'Location',
    dueDate: 'Due date',
    calibratedDate: 'Calibrated date',
    certificateNo: 'Certificate No.',
    result: 'Result',
    calibratedBy: 'Calibrated by',
    status: 'Status',
    statusHsd: 'Validity',
    valid: 'Valid',
    expiring: 'Expiring',
    expired: 'Expired',
    unknown: 'Not calibrated',
    actions: 'Actions',
    edit: 'Edit',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    loading: 'Loading...',
    empty: 'No devices yet',
    requiredFields: 'Please fill in required fields',
    saved: 'Saved',
    saveError: 'Save error',
  },
});

export default function registerCalibrationFrontend(app, router) {
  router.addRoute({
    path: '/calibration',
    component: CalibrationBaseView,
    children: [
      { path: 'devices', name: 'CalibrationList', component: CalibrationListView },
    ],
  });
}
