import { i18n } from '../../../plugins/i18n.js';
import NCRBaseView   from './NCRBaseView.vue';
import NCRListView   from './NCRListView.vue';
import NCRDetailView from './NCRDetailView.vue';

i18n.global.mergeLocaleMessage('vi', {
  ncr: {
    loading: 'Đang tải...',
    cancel: 'Hủy',
    error: 'Đã xảy ra lỗi',
    menu: 'NCR',
    list: {
      title: 'Danh sách điểm không phù hợp (NCR)',
      subtitle: 'Sổ đăng ký báo cáo không phù hợp (NCR Register)',
      create: 'Tạo NCR',
      detail: 'Chi tiết',
      filter: 'Lọc',
      empty: 'Không có NCR nào',
      allStatus: 'Tất cả trạng thái',
      allSeverity: 'Tất cả mức độ',
      allSla: 'Tất cả SLA',
    },
    stats: {
      total: 'Tổng NCR',
      open: 'Đang mở',
      closed: 'Đã đóng',
      overdue: 'Quá hạn',
    },
    create: {
      title: 'Tạo NCR mới',
      creating: 'Đang tạo...',
      titleRequired: 'Tiêu đề là bắt buộc',
      error: 'Lỗi tạo NCR',
      sourceRefPlaceholder: 'ID Kiểm tra / MIR liên kết',
      userIdPlaceholder: 'ID người dùng',
    },
    detail: {
      title: 'Chi tiết NCR',
      back: 'Danh sách',
      actions: 'Thao tác xử lý',
      formTitle: 'Phiếu NCR (QAP-09)',
      workflow: 'Quy trình xử lý 7 bước',
      noTransition: 'Không có bước chuyển tiếp',
      assignLabel: 'Giao xử lý:',
      assignBtn: 'Giao',
      assignRequired: 'Cần chọn người được giao',
      assignOk: 'Đã giao xử lý NCR',
      closeBtn: 'Đóng NCR',
      closeOk: 'Đã đóng NCR',
      capaTitle: 'Hành động khắc phục / phòng ngừa (CAPA)',
      addAction: 'Thêm hành động',
      actionAdded: 'Đã thêm hành động CAPA',
      noCapa: 'Chưa có hành động CAPA nào',
      verifyBtn: 'Xác minh',
      verifyOk: 'Đã xác minh hành động',
      history: 'Lịch sử',
      holdFlag: 'ĐANG GIỮ (HOLD)',
      transitionOk: 'Đã chuyển trạng thái',
      descRequired: 'Mô tả là bắt buộc',
    },
    field: {
      ncrNo: 'Số NCR',
      title: 'Tiêu đề',
      description: 'Mô tả',
      severity: 'Mức độ',
      status: 'Trạng thái',
      sla: 'SLA',
      dueDate: 'Hạn xử lý',
      assignedTo: 'Người được giao',
      sourceType: 'Nguồn phát sinh',
      sourceRef: 'Tham chiếu nguồn',
      project: 'Dự án',
      rootCause: 'Nhóm nguyên nhân gốc',
      action: 'Thao tác',
      actionType: 'Loại hành động',
      owner: 'Người phụ trách',
    },
    status: {
      OPEN: 'Mới mở', ASSIGNED: 'Đã giao', ROOT_CAUSE: 'Phân tích nguyên nhân',
      CAPA_PLAN: 'Lập kế hoạch CAPA', IN_PROGRESS: 'Đang thực hiện',
      VERIFY: 'Chờ xác minh', CLOSED: 'Đã đóng', REOPEN: 'Mở lại',
    },
    severity: { minor: 'Nhẹ', major: 'Nặng', critical: 'Nghiêm trọng' },
    sla: {
      ON_TIME: 'Đúng hạn',
      AT_RISK: 'Sắp tới hạn',
      OVERDUE: 'Quá hạn',
      CLOSED: 'Đã đóng',
    },
    source: { manual: 'Thủ công', inspection: 'Kiểm tra', mir: 'MIR' },
    actionType: { corrective: 'Khắc phục', preventive: 'Phòng ngừa' },
    actionStatus: { open: 'Mở', in_progress: 'Đang làm', done: 'Hoàn thành', verified: 'Đã xác minh' },
    event: {
      created: 'Tạo NCR', transition: 'Chuyển trạng thái', assigned: 'Giao xử lý',
      action_added: 'Thêm hành động', action_verified: 'Xác minh hành động',
      closed: 'Đóng NCR', reopened: 'Mở lại NCR', escalated: 'Cảnh báo',
    },
  },
});

i18n.global.mergeLocaleMessage('en', {
  ncr: {
    loading: 'Loading...',
    cancel: 'Cancel',
    error: 'An error occurred',
    menu: 'NCR',
    list: {
      title: 'Non-Conformance Reports (NCR)',
      subtitle: 'Non-Conformance Report Register',
      create: 'Create NCR',
      detail: 'Details',
      filter: 'Filter',
      empty: 'No NCR found',
      allStatus: 'All statuses',
      allSeverity: 'All severities',
      allSla: 'All SLA',
    },
    stats: {
      total: 'Total NCR',
      open: 'Open',
      closed: 'Closed',
      overdue: 'Overdue',
    },
    create: {
      title: 'Create new NCR',
      creating: 'Creating...',
      titleRequired: 'Title is required',
      error: 'Failed to create NCR',
      sourceRefPlaceholder: 'Linked Inspection / MIR ID',
      userIdPlaceholder: 'User ID',
    },
    detail: {
      title: 'NCR Details',
      back: 'List',
      actions: 'Workflow actions',
      formTitle: 'NCR Form (QAP-09)',
      workflow: '7-Step Workflow',
      noTransition: 'No further transition',
      assignLabel: 'Assign:',
      assignBtn: 'Assign',
      assignRequired: 'Assignee is required',
      assignOk: 'NCR assigned',
      closeBtn: 'Close NCR',
      closeOk: 'NCR closed',
      capaTitle: 'Corrective / Preventive Actions (CAPA)',
      addAction: 'Add action',
      actionAdded: 'CAPA action added',
      noCapa: 'No CAPA actions yet',
      verifyBtn: 'Verify',
      verifyOk: 'Action verified',
      history: 'History',
      holdFlag: 'ON HOLD',
      transitionOk: 'Status changed',
      descRequired: 'Description is required',
    },
    field: {
      ncrNo: 'NCR No', title: 'Title', description: 'Description', severity: 'Severity',
      status: 'Status', sla: 'SLA', dueDate: 'Due date', assignedTo: 'Assigned to',
      sourceType: 'Source', sourceRef: 'Source ref', project: 'Project',
      rootCause: 'Root cause category', action: 'Action', actionType: 'Action type', owner: 'Owner',
    },
    status: {
      OPEN: 'Open', ASSIGNED: 'Assigned', ROOT_CAUSE: 'Root cause',
      CAPA_PLAN: 'CAPA plan', IN_PROGRESS: 'In progress',
      VERIFY: 'Verify', CLOSED: 'Closed', REOPEN: 'Reopened',
    },
    severity: { minor: 'Minor', major: 'Major', critical: 'Critical' },
    sla: {
      ON_TIME: 'On time',
      AT_RISK: 'At risk',
      OVERDUE: 'Overdue',
      CLOSED: 'Closed',
    },
    source: { manual: 'Manual', inspection: 'Inspection', mir: 'MIR' },
    actionType: { corrective: 'Corrective', preventive: 'Preventive' },
    actionStatus: { open: 'Open', in_progress: 'In progress', done: 'Done', verified: 'Verified' },
    event: {
      created: 'NCR created', transition: 'Status change', assigned: 'Assigned',
      action_added: 'Action added', action_verified: 'Action verified',
      closed: 'NCR closed', reopened: 'NCR reopened', escalated: 'Escalation',
    },
  },
});

export default function registerNCRFrontend(app, router) {
  router.addRoute({
    path: '/ncr',
    component: NCRBaseView,
    children: [
      { path: '',     name: 'NCRList',   component: NCRListView },
      { path: ':id',  name: 'NCRDetail', component: NCRDetailView },
    ],
  });
}
